version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
    - echo Installing
  pre_build:
    commands:
    - echo Installing source NPM dependencies...
    - npm install
  build:
    commands:
    - npm run build
    - ls
  post_build:
    commands:
    - echo Build completed on `date`
    - ls
artifacts:
  files:
  - "**/dist/**/*"
  - "**/scripts/**"
  - "**/appspec.yml"
